# Generated by Django 2.2 on 2019-04-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
